name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - demo-
  pull_request:
    branches:
      - demo-
      
jobs:
  call-workflow:
    uses: Hemanth-sep29/demo/.github/workflows/reusableWorkflow.yml@demo-g
    secrets: inherit
