name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - test1
  pull_request:
    branches:
      - test1
      
jobs:
  call-workflow:
    uses: Hemanth-Oct1/demo/.github/workflows/reusableWorkflow.yml@test1
    secrets: inherit
